version: '3'
services:
  trade-nginx:
    container_name: trade-nginx
    build:
      context: ./trade/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./trade:/app
    depends_on:
      - trade-php-fpm
    ports:
      - "8080:80"   # http
  
  trade-php-fpm:
    container_name: trade-php-fpm
    build:
      context: ./trade/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./trade:/app
    depends_on:
      - trade-postgres
  
  trade-php-cli:
    container_name: trade-php-cli
    build:
      context: ./trade/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./trade:/app
      - composer:/root/.composer/cache
    depends_on:
      - trade-postgres
  
  trade-postgres:
    container_name: trade-postgres
    image: postgres:11.2-alpine
    volumes:
      - trade-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  trade-redis:
    image: redis:3.0-alpine
    volumes:
      - trade-redis2:/data
    command:
      - 'redis-server'
      - '--requirepass secret'

  trade-node-watch:
    image: node:12.7-alpine
    volumes:
      - ./trade:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  
  trade-node:
    image: node:12.7-alpine
    volumes:
      - ./trade:/app
    working_dir: /app

  mailer:
    container_name: mailer
    image: mailhog/mailhog
    ports:
      - "8081:8025"
      
volumes:
  trade-postgres:
  trade-redis2:
  composer:
