version: '3'
services:
  tires-nginx:
    container_name: tires-nginx
    build:
      context: ./tires/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./tires:/App
    depends_on:
      - tires-php-fpm
    ports:
      - "8080:80"   # http
  
  tires-php-fpm:
    container_name: tires-php-fpm
    build:
      context: ./tires/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./tires:/App
    depends_on:
      - tires-postgres
  
  tires-php-cli:
    container_name: tires-php-cli
    build:
      context: ./tires/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./tires:/App
    depends_on:
      - tires-postgres
  
  tires-postgres:
    container_name: tires-postgres
    image: postgres:11.2-alpine
    volumes:
      - tires-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: App
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: App
    ports:
      - "54321:5432"

volumes:
  tires-postgres:
